export const feelings = [
  { id: 1, label: 'Joyful', value: 'joyful' },
  { id: 2, label: 'Down', value: 'down' },
  { id: 3, label: 'Anxious', value: 'anxious' },
  { id: 4, label: 'Calm', value: 'calm' },
  { id: 5, label: 'Excited', value: 'excited' },
  { id: 6, label: 'Frustrated', value: 'frustrated' },
  { id: 7, label: 'Lonely', value: 'lonely' },
  { id: 8, label: 'Grateful', value: 'grateful' },
  { id: 9, label: 'Overwhelmed', value: 'overwhelmed' },
  { id: 10, label: 'Motivated', value: 'motivated' },
  { id: 11, label: 'Irritable', value: 'irritable' },
  { id: 12, label: 'Peaceful', value: 'peaceful' },
  { id: 13, label: 'Tired', value: 'tired' },
  { id: 14, label: 'Hopeful', value: 'hopeful' },
  { id: 15, label: 'Confident', value: 'confident' },
  { id: 16, label: 'Stressed', value: 'stressed' },
  { id: 17, label: 'Content', value: 'content' },
  { id: 18, label: 'Disappointed', value: 'disappointed' },
  { id: 19, label: 'Optimistic', value: 'optimistic' },
  { id: 20, label: 'Restless', value: 'restless' },
];
